<?php echo Tag::css("jquery-ui") ?>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<?php echo Tag::js("jquery/jquery-ui") ?>
<script type="text/javascript">
$(document).ready(function(){
	var availableTags;
	$.ajax({
		url:"../../index/get_empresas",
		async:false,
		success:function(r){
			availableTags = r;
			console.log(availableTags)

		}
	})
	var box = $("#usuarios_empresa");
	box.autocomplete({
		source: availableTags
	});
})
</script>
<div id="page-wrapper">
	<div class="row">	
		<h1>Editar Usuario</h1>
		<?php View::content() ?>
			<div class="col-lg-6">
				<?php echo Form::open("","post",'role="form"') ?>
				<div class="form-group">
					<label>Nombre de Usuario</label>
					<?php echo Form::hidden("usuarios.id") ?>
					<?php echo Form::text("usuarios.nombre",'class="form-control" placeholder="Nombre de Usuario" required') ?>
					<p class="help-block">Escribe el Nombre de Usuario</p>
				</div>
				<div class="form-group">
					<label>Password</label>
					<?php echo Form::pass("usuarios.clave11",'class="form-control" placeholder="Password" ') ?>
					<?php echo Form::hidden("usuarios.clave") ?>
					<p class="help-block">Escribe la clave del usuario</p>
				</div>
				<div class="form-group">
					<label>Repetir la Password</label>
					<?php echo Form::pass("usuarios.clave22",'class="form-control" placeholder="Repetir-Password" ') ?>

					<p class="help-block">Repetir la Password</p>
				</div>
				<div class="form-group">
					<label>Empresa</label>
					<?php echo Form::text("usuarios.empresa",'class="form-control" placeholder="Empresa" required') ?>
					<p class="help-block">Escribe la Empresa, Puede que si coloca una letra aparezca una ayuda...</p>
				</div>
				<div class="form-group">
					<label>Email</label>
					<?php echo Form::email("usuarios.email",'class="form-control" placeholder="Email" required') ?>
					<p class="help-block">Escribe el email para a futuro enviar correos automaticos</p>
				</div>
				<div class="form-group">
					<label>Role</label>
					<select name="usuarios[rol]" class="form-control" id="">
						<?php if ($usuarios->rol == "C"): ?>
							
							<option value="C">Seleccione un Role</option>
							<option value="C" selected>Operador Externo</option>
							<option value="I">Operador Interno</option>
							<option value="U">Cliente</option>
							<option value="A">Administrador</option>
						<?php endif ?>
						<?php if ($usuarios->rol == "I"): ?>
							
							<option value="C">Seleccione un Role</option>
							<option value="C" >Operador Externo</option>
							<option value="I" selected>Operador Interno</option>
							<option value="U">Cliente</option>
							<option value="A">Administrador</option>
						<?php endif ?>		
						<?php if ($usuarios->rol == "U"): ?>
							
							<option value="C">Seleccione un Role</option>
							<option value="C" >Operador Externo</option>
							<option value="I" >Operador Interno</option>
							<option value="U" selected>Cliente</option>
							<option value="A">Administrador</option>
						<?php endif ?>	
						<?php if ($usuarios->rol == "A"): ?>
							
							<option value="C">Seleccione un Role</option>
							<option value="C" >Operador Externo</option>
							<option value="I" >Operador Interno</option>
							<option value="U" >Cliente</option>
							<option value="A" selected>Administrador</option>
						<?php endif ?>
						<?php if ($usuarios->rol == ""): ?>
							
							<option value="C" selected>Seleccione un Role</option>
							<option value="C" >Operador Externo</option>
							<option value="I" >Operador Interno</option>
							<option value="U" >Cliente</option>
							<option value="A" selected>Administrador</option>
						<?php endif ?>																	
					</select>
					<p class="help-block">Selecciona un role de usuario</p>
				</div>
				<button type="submit" class="btn btn-default">Editar Usuario</button>
<br>
<br>
			</form>
		</div>	
	</div>
</div>
