
<div id="page-wrapper">
	<div class="row">
		
		<?php View::content() ?>
		<h1>Lista de Usuarios</h1>

		<div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            DataTables Advanced Tables
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Nombre</th>
                                            <th>Empresa</th>
                                            <th>Rol</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    	<?php foreach ($usuarios as $key => $value): ?>
                                    		
	                                        <tr class="odd gradeX">
	                                            <td class="center"><?php echo $value->id ?></td>
	                                            <td class="center"><?php echo $value->nombre ?></td>
	                                            <td class="center"><?php echo $value->empresa ?></td>
	                                            <td class="center">
	                                            	<?php switch ($value->rol) {
	                                            		case 'A':
	                                            			echo "Administrador";
	                                            			break;
	                                            		case 'I':
	                                            			echo "Operador Interno";
	                                            			break;	                                            			
	                                            		case 'C':
	                                            			echo "Operador Externo";
	                                            			break;	 
	                                            		case 'U':
	                                            			echo "Cliente";
	                                            			break;	                                            			         
	                                            	} ?>
	                                            	
	                                            </td>
	                                          <td class="center">
	                                          	<div class="btn-group" role="group" aria-label="...">
	                                          		<?php echo Html::link("usuarios/edit/{$value->id}","",'class="glyphicon glyphicon-edit btn btn-default"') ?>
	                                          		<?php echo Js::link("usuarios/del/{$value->id}","","Esta Seguro?",'glyphicon glyphicon-remove btn btn-default') ?>
												</div>
	                                          </td>
	                                        </tr>
                                    	<?php endforeach ?>
                                       
                            
                                    </tbody>
                                </table>
                            </div>
                      
                        </div>
                        <!-- /.panel-body -->
                    </div>
		</div>		
	</div>
</div>
<br>
    <script src="<?php echo PUBLIC_PATH ?>bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="<?php echo PUBLIC_PATH ?>bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="<?php echo PUBLIC_PATH ?>dist/js/sb-admin-2.js"></script>
	<?php echo Tag::js("jquery/jquery.kumbiaphp") ?>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>