<div id="page-wrapper">
	<div class="row">
		<h1>Dar de Alta Un Contrato</h1>
		<?php View::content() ?>
		<div class="col-lg-6">
		<?php echo Form::openMultipart('') ?>
		    <div class="form-group">
		    
		    	<label>Ingrese un archivo .pdf</label>	
			    <?php echo Form::file('archivo') ?>
			    <?php echo Form::hidden('oculto', NULL, '1') //para saber si se envió el form ?>
		    </div>
		    <div class="form-group">
		    	<label>Empresa</label>
		    	<?php $pertenece = Load::model("usuarios")->find() ?>
		    	<?php foreach ($pertenece as $key => $value): ?>
		    		<?php $array[$value->id] = $value->nombre  ?>
		    	<?php endforeach ?>
		    	<?php echo Form::select("contratos.pertenece_a",$array,"class='form-control'") ?>
		    	<?php echo Form::hidden("contratos.creado_por",null,Auth::get("id") ? Auth::get("id") : false) ?>
		    </div>
		    <div class="form-group">
		    	<label>Numero de Preforma</label>
		    	<?php echo Form::text("contratos.numero_preforma","class='form-control'") ?>
		    </div>
		    <div class="form-group">
		    	<label>Descripcion</label>
		    	<?php echo Form::textarea("contratos.descripcion","class='form-control'") ?>
		    </div>
		    <?php echo Form::submit('Dar de Alta','class="btn btn-default"') ?>
		<?php echo Form::close() ?>
		</div>
	</div>
</div>