<div id="page-wrapper">
	<div class="row">	
		<h1>Editar Tipo de Documento</h1>
		<?php View::content() ?>
			<div class="col-lg-6">
				<?php echo Form::open() ?>
					<div class="form-group">
						<label>Tipo de Documento</label>
						<?php echo Form::hidden("tipos.id") ?>
						<?php echo Form::text("tipos.tipo","class='form-control' placeholder='Tipo de Documento Nuevo'") ?>
						<p class="help-block">Tipo de Documento</p>
					</div>
					<div class="form-group">
						<label>Descripcion</label>
						<?php echo Form::text("tipos.descripcion","class='form-control' placeholder='Breve Descripcion'") ?>
						<p class="help-block">Breve descripcion del tipo de documento</p>
					</div>
					<?php echo Form::submit("Editar","class='btn btn-default'") ?>
				<?php echo Form::close() ?>
			</div>
	</div>
</div>