<div id="page-wrapper">
	<div class="row">
		<h1>Subir Nuevo Documento</h1>
		<?php View::content() ?>
		<div class="col-lg-8">
		<?php echo Html::link("contratos/ver/$contrato","Ver Contrato") ?>
				<?php echo Form::openMultipart('') ?>
		    <div class="form-group">
		    
		    	<label>Ingrese un archivo .pdf</label>	
		    	<?php echo Form::hidden("documentos.contratos_id",null,$contrato) ?>
			    <?php echo Form::file('archivo',"required") ?>
			    <?php echo Form::hidden('oculto', NULL, '1') //para saber si se envió el form ?>
		    </div>
		    <div class="form-group">
		    	<label>Empresa</label>
		    	<?php $pertenece = Load::model("usuarios")->find() ?>
		    	<?php foreach ($pertenece as $key => $value): ?>
		    		<?php $array[$value->id] = $value->nombre  ?>
		    	<?php endforeach ?>
		    	<?php echo Form::select("contratos.pertenece_a",$array,"class='form-control'") ?>
		    	<?php echo Form::hidden("documentos.subido_por",null,Auth::get("id") ? Auth::get("id") : false) ?>
		    </div>
		    <div class="form-group">
		    	<label>Tipo de Documento</label>
		    	<?php $tipos = Load::model("tipos")->find(); ?>
		    	<select name="documentos[tipo_documento]" id="" required class="form-control">
		    		<option value="">Seleccione</option>
			    	<?php foreach ($tipos as $key => $value): ?>
			    		<option value="<?php echo $value->id ?>"> <?php echo $value->tipo ?> </option>
			    	<?php endforeach ?>
		    			
		    		
		    	</select>
		    </div>
		    <div class="form-group">
		    	<label>Descripcion</label>
		    	<?php echo Form::textarea("contratos.descripcion","class='form-control' placeholder='Breve Descripcion, no obligatoria'") ?>
		    </div>
		    <div class="form-group">
		    	<label>Estado</label>
		    	<select name="documentos[estado]" class="form-control" id="">
		    		<option value="">Seleccione</option>
		    		<option value="completado">Completado</option>
		    		<option value="completado_y_enviado">Completado y Enviado</option>
		    		<option value="pendiente">Pendiente</option>
		    	</select>
		    </div>
		    <div class="form-group">
		    	<label>DHL</label>
		    	<?php echo Form::text("documentos.dhl","class='form-control' placeholder='Dhl en caso de que exista'") ?>
		    </div>
		    <?php echo Form::submit('Dar de Alta','class="btn btn-default"') ?>
		<?php echo Form::close() ?>
		</div>
	</div>
</div>